name: flutter_news
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service Locator
  get_it: ^7.6.6

  #dateFormat
  intl: ^0.18.1

  #Database
  floor: ^1.4.2

  #requests
  retrofit: ^3.0.1

  #Hooks
  flutter_hooks: ^0.18.3

  #Cache images
  cached_network_image: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2

flutter:

  uses-material-design: true